[programs.devnet]
main1 = "3da9USJv9BBFdnuWQsMxSE4vArxS1aEzXBnFsBaWdkKh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/shreyjay0/.config/solana/id.json"

[scripts]
test = "node tests/main1.js"
